export const mockData = [
  {
    Title: "Becoming Bond",
    Year: "2017",
    Rated: "TV-MA",
    Released: "20 May 2017",
    Runtime: "95 min",
    Genre: "Documentary, Biography, Comedy",
    Director: "Josh Greenbaum",
    Writer: "Josh Greenbaum",
    Actors: "George Lazenby, Josh Lawson, Kassandra Clementi",
    Plot: "A look at the troubled acting career of George Lazenby and his short-lived association with James Bond.",
    Language: "English",
    Country: "United States",
    Awards: "2 wins & 2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZDRiNGIzYWEtYzY3Zi00MTcwLWFkOWItZjEyYjg0OGMxMGQ5XkEyXkFqcGdeQXVyMjM4NjQxMDA@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "78%",
      },
      {
        Source: "Metacritic",
        Value: "65/100",
      },
    ],
    Metascore: "65",
    imdbRating: "7.5",
    imdbVotes: "3,035",
    imdbID: "tt6110504",
    Type: "movie",
    DVD: "20 May 2017",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond 007: Everything or Nothing",
    Year: "2003",
    Rated: "T",
    Released: "18 Feb 2004",
    Runtime: "N/A",
    Genre: "Action, Adventure, Sci-Fi, Thriller",
    Director: "Scot Bayless",
    Writer:
      "Danny Bilson (story), Paul De Meo (story), Bruce Feirstein, Ian Fleming (characters), Nuno Miranda (adaptation), Nuno Miranda (translation)",
    Actors: "Pierce Brosnan, John Cleese, Willem Dafoe, Judi Dench",
    Plot: "007 and Serena St. Germaine discover that Katya Nadonova's project, nanobots designed to repair nuclear reactors; have been stolen by Nikolai Diavolo. Together the two set off to new Orleans and beyond to confront Diavolo.",
    Language: "English, Russian, Spanish",
    Country: "USA",
    Awards: "1 win & 2 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzhiNjgxNGMtMzg0ZS00ODMwLTk5MTYtYzI0NDBmOThlZjY3XkEyXkFqcGdeQXVyNTEwNDY2MjU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.9",
    imdbVotes: "2,222",
    imdbID: "tt0366629",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Demon Slayer: Kimetsu no Yaiba - Sibling's Bond",
    Year: "2019",
    Rated: "N/A",
    Released: "29 Mar 2019",
    Runtime: "105 min",
    Genre: "Animation, Action, Fantasy",
    Director: "Haruo Sotozaki",
    Writer: "Koyoharu Gotouge",
    Actors: "Zach Aguilar, Ryan Bartley, Brook Chalmers",
    Plot: "Tanjiro finds his family slaughtered and the lone survivor, his sister Nezuko Kamado, turned into a Demon. To his surprise, however, Nezuko still shows signs of human emotion and thought. Thus begins Tanjiro's journey to seek out ...",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmU0NjY3ZDAtYWVkNC00ZjI2LTk5MGItNGRiZTdlYWQyNjQxXkEyXkFqcGdeQXVyMTA5NzUzODM4._V1_SX300.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "2,031",
    imdbID: "tt14888860",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond 007: Blood Stone",
    Year: "2010",
    Rated: "T",
    Released: "02 Nov 2010",
    Runtime: "N/A",
    Genre: "Action, Adventure, Thriller",
    Director: "Kate Saxon",
    Writer: "Bruce Feirstein (story), Adam Foshko (dialogue)",
    Actors: "Daniel Craig, Judi Dench, Joss Stone, Rory Kinnear",
    Plot: "007 is tasked with saving Great Britain from a maniac who's gotten his hands on military grade bio weapons.",
    Language: "English",
    Country: "USA",
    Awards: "1 win & 4 nominations.",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTcxMzE4NDg0NF5BMl5BanBnXkFtZTgwMjg5Mjc1MDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.5",
    imdbVotes: "1,945",
    imdbID: "tt1692489",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Ek Rishtaa: The Bond of Love",
    Year: "2001",
    Rated: "Not Rated",
    Released: "18 May 2001",
    Runtime: "174 min",
    Genre: "Drama",
    Director: "Suneel Darshan",
    Writer: "Suneel Darshan, Robin Bhatt, K.K. Singh",
    Actors: "Amitabh Bachchan, Rakhee Gulzar, Akshay Kumar",
    Plot: "Vijay Kapoor, a wealthy businessman and his family are deceived by Rajesh, Vijay Kapoor's employee and son in law. A struggle begins by both father-son duos to regain their business and position.",
    Language: "Hindi",
    Country: "India",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmNmOTM5ZGUtNTFiZS00M2E2LTk2NzAtNTJlZmQ0MGQyOTMwXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.2",
    imdbVotes: "1,721",
    imdbID: "tt0284083",
    Type: "movie",
    DVD: "01 Aug 2001",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Bond",
    Year: "1918",
    Rated: "N/A",
    Released: "20 Oct 1969",
    Runtime: "10 min",
    Genre: "Short, Comedy",
    Director: "Charles Chaplin",
    Writer: "Charles Chaplin",
    Actors: "Charles Chaplin, Edna Purviance, Albert Austin",
    Plot: "Charlie and friends illustrate various bonds in life and the most important, Liberty Bonds for the war...",
    Language: "None, English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmE3MzIxMDMtNzJiOC00YzY5LTg5ZWUtNTZiZDM1Y2ZmNDYyXkEyXkFqcGdeQXVyNDUzNzExOTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.4",
    imdbVotes: "1,126",
    imdbID: "tt0008907",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Mad Mission 3: Our Man from Bond Street",
    Year: "1984",
    Rated: "N/A",
    Released: "26 Jan 1984",
    Runtime: "81 min",
    Genre: "Action, Comedy",
    Director: "Hark Tsui",
    Writer: "Larry Dolgin, Raymond Pak-Ming Wong",
    Actors: "Samuel Hui, Karl Maka, Sylvia Chang",
    Plot: "A master thief is duped by lookalikes for James Bond and the Queen of England into stealing a valuable gem from a heavily guarded location then must help the police recover it.",
    Language: "Cantonese, English",
    Country: "Hong Kong",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWNkNDkzNjUtZWEwMy00YWIyLWFmNzctNjY5N2YyNDA5OGZmXkEyXkFqcGdeQXVyNDkyMzMyODM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.8",
    imdbVotes: "1,065",
    imdbID: "tt0088457",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond of Silence",
    Year: "2010",
    Rated: "TV-PG",
    Released: "23 Aug 2010",
    Runtime: "98 min",
    Genre: "Drama",
    Director: "Peter Werner",
    Writer: "Brian D. Young, Edithe Swensen, Teena Booth",
    Actors: "Kim Raver, Greg Grunberg, Charlie McDermott",
    Plot: "Starring Kim Raver and Greg Grunberg. A widow must pierce the veil of secrecy uniting a group of teens and their parents in order to find out how her husband died. Based on a true story.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWRlZjVkMGQtNGVjYS00NWJiLThjZjItYjg0OGRhYmY4NTZjXkEyXkFqcGdeQXVyMjcxNjI4NTk@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.0",
    imdbVotes: "1,014",
    imdbID: "tt1659192",
    Type: "movie",
    DVD: "05 Jul 2011",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond",
    Year: "2022",
    Rated: "PG-13",
    Released: "25 Nov 2022",
    Runtime: "114 min",
    Genre: "Animation, Action, Adventure",
    Director: "Yasuhito Kikuchi",
    Writer: "Fuse",
    Actors: "Tia Lynn Ballard, Ben Balmaceda, Bryson Baugus",
    Plot: "Corporate worker Mikami is stabbed by a random killer, is reborn to an alternate world. But he is reborn as a slime. He is Thrown into this new world with the name Rimuru, he begins his quest to create a world that's welcoming to ...",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTRlMjMzNjItYjJmMi00NjBhLTgxZmYtMzhlYjE1ODlhNjE1XkEyXkFqcGdeQXVyNzI3NjY3NjQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
      {
        Source: "Metacritic",
        Value: "41/100",
      },
    ],
    Metascore: "41",
    imdbRating: "6.8",
    imdbVotes: "735",
    imdbID: "tt15467380",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$1,588,491",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond Girls Are Forever",
    Year: "2002",
    Rated: "Unrated",
    Released: "06 Nov 2002",
    Runtime: "46 min",
    Genre: "Documentary",
    Director: "John Watkin",
    Writer: "Maryam d'Abo, John Watkin",
    Actors: "Maryam d'Abo, Halle Berry, Ursula Andress",
    Plot: 'Through vintage film clips of past Bond movie epics, and with the participation of several former "Bond Girls", the documentary traced the evolution of the typical James Bond heroine from decorative damsel in distress to gutsy par...',
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjMwNTMzNjM5OF5BMl5BanBnXkFtZTgwOTY4OTk1MDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.5",
    imdbVotes: "734",
    imdbID: "tt0353252",
    Type: "movie",
    DVD: "31 Jan 2006",
    BoxOffice: "N/A",
    Production: "Metro-Goldwyn-Mayer",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Jatt James Bond",
    Year: "2014",
    Rated: "Not Rated",
    Released: "25 Apr 2014",
    Runtime: "220 min",
    Genre: "Comedy",
    Director: "Rohit Jugraj",
    Writer: "Jass Grewal, Jatinder-Lall, Ed D Singh",
    Actors: "Gippy Grewal, Zareen Khan, Gurpreet Ghuggi",
    Plot: "Shinda was mistreated by his relatives therefore he finds other ways to have his love Laali. Shinda and his two other friends come up with a plan to solve all of their problems.",
    Language: "Punjabi",
    Country: "India",
    Awards: "3 wins",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWVmNjQ2YmYtY2M4ZS00NDdkLTljZmUtYTZkNmNjM2FhMWU3XkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.7",
    imdbVotes: "733",
    imdbID: "tt3732110",
    Type: "movie",
    DVD: "02 Dec 2016",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Mr. Bond",
    Year: "1992",
    Rated: "Not Rated",
    Released: "16 Apr 1992",
    Runtime: "127 min",
    Genre: "Action, Adventure, Thriller",
    Director: "Raj N. Sippy",
    Writer: "Mohinder Ashish, Iqbal Durrani",
    Actors: "Akshay Kumar, Sheeba Agarwal, Saathi Ganguly",
    Plot: "Mr. Bond is an honest, dedicated and capable police officer in Bombay's police force. He faces the toughest case of a lifetime when he must rescue some small children abducted and held as hostages by the underworld don Dragon.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTYzZjI1MWEtMDgxYi00ZGNmLThkOWEtNmJlOWFiZjNmNjE0XkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "3.3",
    imdbVotes: "673",
    imdbID: "tt0104927",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond Jr.",
    Year: "1991–1992",
    Rated: "TV-Y",
    Released: "16 Sep 1991",
    Runtime: "30 min",
    Genre: "Animation, Action, Adventure",
    Director: "N/A",
    Writer: "Andy Heyward, Robby London, Michael G. Wilson",
    Actors: "Corey Burton, Jeff Bennett, Jan Rabson",
    Plot: "The nephew of MI6's greatest spy carries on his uncle's legacy by combating a rogues' gallery of new and familiar villains with the help of his schoolmates.",
    Language: "English",
    Country: "United States",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTQ2NjkzNTA1N15BMl5BanBnXkFtZTcwMzM1Mjg4NA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.0",
    imdbVotes: "665",
    imdbID: "tt0283744",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "James Bond in Agent Under Fire",
    Year: "2001",
    Rated: "T",
    Released: "13 Nov 2001",
    Runtime: "N/A",
    Genre: "Action, Adventure, Crime, Family, Thriller",
    Director: "N/A",
    Writer:
      "Danny Bilson, Paul De Meo, Ian Fleming (characters), Nuno Miranda (Portuguese translation and adaptation)",
    Actors: "Adam Blackwood, Caron Pascoe, Miles Anderson, Sydney Rainin-Smith",
    Plot: "After rescuing a CIA agent being held hostage, Bond travels the globe in pursuit of Nigel Bloch, a brilliant madman who is working with a mysterious corporation in a plot involving cloning, kidnapping, and political manipulation.",
    Language: "English",
    Country: "USA, Canada",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2NjMjRmZDMtOTVmOC00MzQ4LWE4ZWYtOTE4NWQyMGVlYjlmXkEyXkFqcGdeQXVyNTEwNDY2MjU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "638",
    imdbID: "tt0295846",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Natsume's Book of Friends the Movie: Ephemeral Bond",
    Year: "2018",
    Rated: "N/A",
    Released: "29 Sep 2018",
    Runtime: "104 min",
    Genre: "Animation, Drama, Fantasy",
    Director: "Hideki Itô, Takahiro Ômori",
    Writer: "Yuki Midorikawa, Sadayuki Murai",
    Actors: "Hiroshi Kamiya, Ayumi Fujimura, Kazuhiko Inoue",
    Plot: "An orphaned teen encounters a supernatural creature that has the ability to look human.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmY1ODRkNDMtNjNiMS00MjU2LWFkYTgtODkyMTI2ZmExYzYwXkEyXkFqcGdeQXVyNzEyMDQ1MDA@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "548",
    imdbID: "tt9081300",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The James Bond Story",
    Year: "1999",
    Rated: "Unrated",
    Released: "08 Jan 2000",
    Runtime: "52 min",
    Genre: "Documentary",
    Director: "Chris Hunt",
    Writer: "N/A",
    Actors: "Sean Connery, Michael G. Wilson, Roger Moore",
    Plot: "One Bond is not enough, and this documentary proves it! The James Bond Story celebrates the 39th Anniversary of James Bond in the cinema.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTg1ODc0MjkzMF5BMl5BanBnXkFtZTcwMDY2NzEyMQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "510",
    imdbID: "tt0239074",
    Type: "movie",
    DVD: "25 Apr 2000",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Nims Bond",
    Year: "2008",
    Rated: "N/A",
    Released: "06 Feb 2008",
    Runtime: "115 min",
    Genre: "Comedy, Romance",
    Director: "Ahmad El-Badri, Umar Gabr",
    Writer: "Tareq Abdulgalil, Mohamed Youssef",
    Actors: "Hani Ramzi, Ahmed Rateb, Lotfy Labib",
    Plot: "A clumsy police officer who is a huge fan of the James Bond movies finds himself assigned to solve a murder.",
    Language: "Arabic",
    Country: "Egypt",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZGQ5Mzc4NmMtMDU4Yy00MzczLTliMmYtM2U3MjE3Y2UwYjhmL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjQwMjk0NjI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "3.9",
    imdbVotes: "491",
    imdbID: "tt1596777",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title:
      "One Piece: Episode of Sabo - Bond of Three Brothers, a Miraculous Reunion and an Inherited Will",
    Year: "2015",
    Rated: "N/A",
    Released: "22 Aug 2015",
    Runtime: "N/A",
    Genre: "Animation",
    Director: "Gô Koga",
    Writer: "Eiichirô Oda, Hirohiko Uesaka",
    Actors: "Randy E. Aguebor, Greg Ayres, Daniel Baugh",
    Plot: "This TV Special covers the story of Sabo. From his childhood with Luffy and Ace until his reunion with Luffy in Dressrossa from his point of view.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTk0NDAyMTktMjQwMC00NjVlLTk4ZTktMmI5MGU4NzU2ZGQ4XkEyXkFqcGdeQXVyNDkwMzY5NjQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "458",
    imdbID: "tt6597356",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond Supports International Women's Day",
    Year: "2011",
    Rated: "N/A",
    Released: "05 Mar 2011",
    Runtime: "2 min",
    Genre: "Short, Action",
    Director: "Sam Taylor-Johnson",
    Writer: "Jane Goldman",
    Actors: "Judi Dench, Daniel Craig",
    Plot: "This short film is made by 'We Are Equals' to celebrate International Women's Day. James Bond video for international women's day shows 007's feminine side. Daniel Craig and Dame Judi Dench team up for two-minute film highlighting...",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmQ4OTlmNTUtMmQ1NC00YmI0LTgxYTItYjU5NjJkZjFkZTMyXkEyXkFqcGdeQXVyMjExMDE1MzQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.7",
    imdbVotes: "369",
    imdbID: "tt1858469",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Anna Bond",
    Year: "2012",
    Rated: "N/A",
    Released: "03 May 2012",
    Runtime: "136 min",
    Genre: "Action, Thriller",
    Director: "Soori",
    Writer: "Duniya Soori",
    Actors: "Puneeth Rajkumar, Priyamani, Nidhi Subbaiah",
    Plot: "",
    Language: "Kannada",
    Country: "India",
    Awards: "1 win & 2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMzIyNGJiNGMtZTgwZS00Zjg4LThhNjYtMzIyYjhlNmMyZDg1XkEyXkFqcGdeQXVyMzQzMDc2MDk@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "4.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "4.3",
    imdbVotes: "324",
    imdbID: "tt2146950",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Boricua's Bond",
    Year: "2000",
    Rated: "R",
    Released: "21 Jun 2000",
    Runtime: "105 min",
    Genre: "Drama",
    Director: "Val Lik",
    Writer: "Val Lik",
    Actors: "Frankie Negron, Val Lik, Ramses Ignacio",
    Plot: "Can a young person in the South Bronx pursue a dream that isn't tied to crime, gang-banging, prostitution, violence, and racism? Tommy is a natural leader and a gifted artist. When Allen, a white kid, moves into the neighborhood w...",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjA5MDA4NTQyNF5BMl5BanBnXkFtZTYwNDk0Mjk5._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.5/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "11%",
      },
      {
        Source: "Metacritic",
        Value: "21/100",
      },
    ],
    Metascore: "21",
    imdbRating: "3.5",
    imdbVotes: "292",
    imdbID: "tt0217287",
    Type: "movie",
    DVD: "01 Feb 2021",
    BoxOffice: "$71,046",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Blood Bond",
    Year: "2011",
    Rated: "N/A",
    Released: "27 Jan 2011",
    Runtime: "86 min",
    Genre: "Action, Thriller",
    Director: "Michael Biehn, Antony Szeto",
    Writer: "Bey Logan, Nicholas Eriksson, Dan Bush",
    Actors: "Michael Biehn, Phoenix Chou, Simon Yam",
    Plot: "A world-renowned spiritual leader arrives in the Asian nation of Purma to give a teaching to the faithful. Accompanying him is a retinue of monks and attendants, including his personal bodyguard, Deva, a beautiful Eurasian girl wi...",
    Language: "English",
    Country: "United States, China",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTkwNTQwNWMtOGUyNS00ZmVmLTk1M2MtMGUyOGFmOWU2YTdkXkEyXkFqcGdeQXVyMjExMzEyNTM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "3.5",
    imdbVotes: "278",
    imdbID: "tt1520399",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Fatal Bond",
    Year: "1991",
    Rated: "R",
    Released: "05 Mar 1992",
    Runtime: "89 min",
    Genre: "Drama, Thriller",
    Director: "Vincent Monton",
    Writer: "Phillip Avalon",
    Actors: "Linda Blair, Jerome Ehlers, Donal Gibson",
    Plot: "A restless hairdresser takes up with a man (Joe Martinez) she knows is wanted by the police. It is only when she realizes that he may be a serial killer, that she starts questioning the relationship.",
    Language: "English",
    Country: "Australia",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmZmNTllZjctYjVhNi00MTA2LTgzMGMtNTRkMDMxMzkxZTEwXkEyXkFqcGdeQXVyMTk5MjAyMjM@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "4.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "4.0",
    imdbVotes: "273",
    imdbID: "tt0104233",
    Type: "movie",
    DVD: "22 May 2017",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "No Time to Die: Official Title Reveal of Bond 25",
    Year: "2019",
    Rated: "N/A",
    Released: "20 Aug 2019",
    Runtime: "1 min",
    Genre: "Short",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Daniel Craig",
    Plot: 'A short video revealing the title of the 25th James Bond movie, "No Time To Die".',
    Language: "English",
    Country: "USA, UK",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjA3ZjhiODUtN2QxYy00MzlhLWFlYzYtZTg1ODQ2YjM0YjY3XkEyXkFqcGdeQXVyMzM3ODE4MzY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.3",
    imdbVotes: "260",
    imdbID: "tt10839440",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond",
    Year: "2015",
    Rated: "N/A",
    Released: "24 Jul 2015",
    Runtime: "142 min",
    Genre: "Action, Comedy",
    Director: "Sai Kishore Macha",
    Writer: "Shyam Ch, Gopimohan, Sai Kishore Macha",
    Actors: "Allari Naresh, Sakshi Chaudhary, Raghu Babu",
    Plot: "A down-to-earth software employee marries a lady without knowing about her past and criminal activities. Halfway through his marriage, he finds out her background and decides to run away, but ultimately comes to terms with his pro...",
    Language: "Telugu",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2IwZDRiOTAtNTUxOC00ZWQxLThlYTYtZTM2NTRmMjEzNmQwXkEyXkFqcGdeQXVyODAzNzAwOTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.5",
    imdbVotes: "257",
    imdbID: "tt4896340",
    Type: "movie",
    DVD: "02 Aug 2018",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Siamese Bond",
    Year: "2020",
    Rated: "N/A",
    Released: "03 Dec 2020",
    Runtime: "80 min",
    Genre: "Drama",
    Director: "Paula Hernández",
    Writer: "Leonel D'Agostino, Paula Hernández",
    Actors: "Rita Cortese, Valeria Lois, Sergio Prina",
    Plot: "Estela and her mother Clota must travel from Junín, where they live, to the town of Costa Bonita, in Necochea, to see some apartments that Estela's father left her.",
    Language: "Spanish",
    Country: "Argentina",
    Awards: "3 wins & 6 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGM0ZjI3OTItNTg3Ni00NDZjLWFjYzktYzJmMmZiOWQ1NTA5XkEyXkFqcGdeQXVyMjY5NjY2NTk@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.0",
    imdbVotes: "256",
    imdbID: "tt13528580",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Happy Anniversary 007: 25 Years of James Bond",
    Year: "1987",
    Rated: "N/A",
    Released: "13 May 1987",
    Runtime: "49 min",
    Genre: "Documentary",
    Director: "Mel Stuart",
    Writer: "Richard Schickel",
    Actors: "Roger Moore, Timothy Dalton",
    Plot: "An hour documentary on the history of Bond for the 25th anniversary of the film series.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWE3NzFlZDItZTllNy00ZGE2LTgwMWYtZWI3ZGQyYjY4ZTNiXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.7",
    imdbVotes: "212",
    imdbID: "tt0223426",
    Type: "movie",
    DVD: "24 Oct 1987",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Sean Connery vs James Bond",
    Year: "2022",
    Rated: "N/A",
    Released: "23 Oct 2022",
    Runtime: "53 min",
    Genre: "Documentary, Action, Biography",
    Director: "Gregory Monro",
    Writer: "Gregory Monro",
    Actors: "Sean Connery, John Boorman, Andy Garcia",
    Plot: "Having become a world star thanks to James Bond, Sean Connery, who died in 2020, has never stopped trying to shed the image of a sexy and slightly brutal macho that stuck to 007. A look back at an eclectic career, carried out with...",
    Language: "English",
    Country:
      "France, Switzerland, Belgium, Poland, Ireland, Austria, Czech Republic, Netherlands, Israel, Brazil",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNmQ0Mzg1NTItNjZjMi00M2ZjLTkxZDEtYzhhYWMzMmVkMmMxXkEyXkFqcGdeQXVyNTM2NTg3Nzg@._V1_SX300.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "209",
    imdbID: "tt22498916",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Free! Timeless Medley: The Bond",
    Year: "2017",
    Rated: "TV-14",
    Released: "22 Apr 2017",
    Runtime: "94 min",
    Genre: "Animation, Sport",
    Director: "Eisaku Kawanami",
    Writer: "Masahiro Yokotani",
    Actors: "Greg Ayres, Tia Lynn Ballard, Christopher Bevins",
    Plot: "Haruka Nanase agree to join the swimming club after a very long time, and together with his friend tries to mend old bond and win in the regional swimming tournament.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmI4NThhYTctOTNiMi00NDE4LTk1ODQtZWY1NmJhOWEzMzViXkEyXkFqcGdeQXVyNjgwNTk4Mg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.3",
    imdbVotes: "207",
    imdbID: "tt6799508",
    Type: "movie",
    DVD: "04 Jan 2019",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The World of James Bond",
    Year: "1995",
    Rated: "G",
    Released: "29 Oct 1995",
    Runtime: "60 min",
    Genre: "Documentary",
    Director: "Paul Hall, Tom Shelly",
    Writer: "Mark Cowen",
    Actors: "Elizabeth Hurley, Chris Connelly, Andie MacDowell",
    Plot: "Elizabeth Hurley hosts a one hour documentary on the history of the James Bond film series to tie in with the seventeenth Bond film, GoldenEye.",
    Language: "English",
    Country: "United States, United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTBhYWYxM2QtMWZhYS00NGYxLWI2Y2MtMDJmZGM2ZjFhZjI5XkEyXkFqcGdeQXVyMTEzNzczMA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.6",
    imdbVotes: "201",
    imdbID: "tt0114982",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Best Ever Bond",
    Year: "2002",
    Rated: "N/A",
    Released: "22 Nov 2002",
    Runtime: "86 min",
    Genre: "Action, Adventure, Documentary",
    Director: "John Piper, Debbie Geller, Sarah Hunt",
    Writer: "Mark Robinson",
    Actors: "Roger Moore, Ken Adam, Michael Apted",
    Plot: "Roger Moore presents the ten best sequences ever to have appeared in the James Bond series, and cast members recall their favourite moments.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWI2OGJkYzUtM2RjMC00M2U5LTkwMTItZDZjNDk3ZjcxNTM3XkEyXkFqcGdeQXVyNzg3ODM4NTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.6",
    imdbVotes: "191",
    imdbID: "tt0342098",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Daniel Craig vs James Bond",
    Year: "2020",
    Rated: "N/A",
    Released: "14 Jan 2020",
    Runtime: "2 min",
    Genre: "Short, Action, Adventure",
    Director: "Miles Jay",
    Writer: "N/A",
    Actors: "Daniel Craig, Blanca Parés",
    Plot: "Starting with a high-speed taxi sequence, Daniel is constantly recognized as James Bond by surprised locals as he hunts down his missing passport.",
    Language: "English, Spanish",
    Country: "United Kingdom, Italy",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjJiNjRjZmItODczYi00YWE4LWJhNGYtNDJmNDllYjdkMzVjXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.3",
    imdbVotes: "184",
    imdbID: "tt11610250",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond",
    Year: "1999",
    Rated: "N/A",
    Released: "30 Jul 1999",
    Runtime: "N/A",
    Genre: "Comedy",
    Director: "Baiju Kottarakkara",
    Writer: "Kaloor Dennis",
    Actors: "Aby, Indrans, Janardanan",
    Plot: "Five friends in hiding after their local business goes bankrupt stumble upon a baby that changes their lives.",
    Language: "Malayalam",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTJlYWYyMTUtNzQ2YS00YmYzLThkMzItOGQ0ZDA0ZWJhNjFkXkEyXkFqcGdeQXVyMjkxNzQ1NDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.0",
    imdbVotes: "165",
    imdbID: "tt0255268",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond of Fear",
    Year: "1956",
    Rated: "N/A",
    Released: "01 Apr 1956",
    Runtime: "66 min",
    Genre: "Drama, Crime",
    Director: "Henry Cass",
    Writer: "John Gilling, Norman Hudis, Digby Wolfe",
    Actors: "Dermot Walsh, Jane Barrett, John Colicos",
    Plot: "An escaped killer hides out by forcing a travelling family to take him with them.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjgxMjU2ZGQtYjU4Mi00ZjFmLTk5NTktMzgzMWQ4MmU1Mzc5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.0",
    imdbVotes: "153",
    imdbID: "tt0279699",
    Type: "movie",
    DVD: "30 Jun 2009",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Parchhayee: Ghost Stories by Ruskin Bond",
    Year: "2019–",
    Rated: "N/A",
    Released: "15 Jan 2019",
    Runtime: "1 min",
    Genre: "Horror, Thriller",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Sumeet Vyas, Isha Talwar, Anurita Jha",
    Plot: "This winter, there's no escaping the shivers as ZEE5 Original 'Parchhayee' is all set to bring to life the most bone-chilling horror tales of celebrated author Ruskin Bond.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDc0MGQ1N2MtNWQzOC00N2U2LWE3MzMtNWVkYzIzNGE2YjliXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.3",
    imdbVotes: "136",
    imdbID: "tt9549012",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "Word Is Bond",
    Year: "2018",
    Rated: "TV-MA",
    Released: "16 Feb 2018",
    Runtime: "87 min",
    Genre: "Documentary, Music",
    Director: "Sacha Jenkins",
    Writer: "N/A",
    Actors: "Anderson .Paak, Brother Ali, Big Daddy Kane",
    Plot: "What was born on the streets of the South Bronx has now taken root globally, and the young poets of New York have helped to spawn regional dialects everywhere. Through dynamic archival footage, in-depth interviews and vertie excur...",
    Language: "English",
    Country: "United States",
    Awards: "1 win",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWM0Mzg5OTMtOTJhMi00NjYzLTg1N2EtZDhlM2NmZmJjNzMzXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.8",
    imdbVotes: "130",
    imdbID: "tt7521000",
    Type: "movie",
    DVD: "01 Mar 2018",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Cubby Broccoli: The Man Behind Bond",
    Year: "2000",
    Rated: "N/A",
    Released: "17 Oct 2000",
    Runtime: "44 min",
    Genre: "Documentary",
    Director: "John Cork",
    Writer: "John Cork",
    Actors: "Patrick Macnee, Barbara Broccoli, Donald Zec",
    Plot: 'Documentary on Albert R. "Cubby" Broccoli and his involvement with the James Bond movies.',
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzMyMjdiYzYtZmYxYy00YWVkLTg0ZTQtNzI2MWExYTQwYWQzXkEyXkFqcGdeQXVyMTQxMjk0Mg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.9",
    imdbVotes: "129",
    imdbID: "tt0306693",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "House of Bond",
    Year: "2017",
    Rated: "N/A",
    Released: "24 Apr 2017",
    Runtime: "148 min",
    Genre: "Drama",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Ben Mingay, Adrienne Pickering, Anne Looby",
    Plot: 'House of Bond tells the rags-to-riches-to-rags tale of controversial business tycoon Alan Bond from the 1960s to the 1990s. It follows the story of a cheeky, knockabout "Ten Pound Pom" who fought his way from the back alleys of Fr...',
    Language: "English",
    Country: "Australia",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZDdhY2RlYjMtZDBhZC00ZWY1LTljYWUtOTA4ZmNlZmQxNzdjXkEyXkFqcGdeQXVyNTY2MzkxMjc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.4",
    imdbVotes: "128",
    imdbID: "tt6231504",
    Type: "series",
    totalSeasons: "1",
    Response: "True",
  },
  {
    Title: "James Bond: In Service of Nothing",
    Year: "2015",
    Rated: "N/A",
    Released: "02 Mar 2015",
    Runtime: "11 min",
    Genre: "Animation, Short, Action",
    Director: "Tyler Gibb",
    Writer: "Tyler Gibb",
    Actors: "Christopher Gee, Tyler Gibb, Damien C. Haas",
    Plot: "An aging former super spy struggles to find his place in a self-absorbed world without borders.",
    Language: "English",
    Country: "Canada",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNWJhODc3Y2ItYTk1Zi00MTRiLWI4NmMtMzhjOWRkNjRjMDNkXkEyXkFqcGdeQXVyMzYzNzc1NjY@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.7",
    imdbVotes: "123",
    imdbID: "tt4540242",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Becoming Bond",
    Year: "2006",
    Rated: "N/A",
    Released: "07 Nov 2006",
    Runtime: "26 min",
    Genre: "Documentary",
    Director: "Rob Done",
    Writer: "N/A",
    Actors: "Barbara Broccoli, Michael G. Wilson, Martin Campbell",
    Plot: "A documentary which shows the creation of Casino Royale (2006).",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWU0MWQzOTAtNGYxOC00ODNjLTkwZTYtZjVjOTY3Nzk3NzY4XkEyXkFqcGdeQXVyMjA5NjIxNDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.8",
    imdbVotes: "123",
    imdbID: "tt0907299",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond Street",
    Year: "1948",
    Rated: "N/A",
    Released: "29 Mar 1950",
    Runtime: "109 min",
    Genre: "Drama",
    Director: "Gordon Parry",
    Writer: "Terence Rattigan, Rodney Ackland, Anatole de Grunwald",
    Actors: "Jean Kent, Roland Young, Kathleen Harrison",
    Plot: "A young British woman is getting married, and as she goes through her trousseau, the stories behind four of the items that were bought on Bond Street in London unfold.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmQxZTMzNTQtN2M4Zi00YThmLTliMzYtZDEwOTc2OGUwMDg4XkEyXkFqcGdeQXVyNDQ3NDM5OQ@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.4",
    imdbVotes: "115",
    imdbID: "tt0039206",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Bond Sound: The Music of 007",
    Year: "2000",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "21 min",
    Genre: "Documentary, Short, Music",
    Director: "John Cork",
    Writer: "Bruce Scivally",
    Actors: "Patrick Macnee, Monty Norman, Byron Lee, John Barry",
    Plot: "Documentary discussing the many songs featured in the James Bond films.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYThlNzM2MmMtNDk0MC00YzM5LTgxZjEtZTMzMmI1ODQ0NDczL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxMjk0Mg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "112",
    imdbID: "tt0307198",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Bond of the Hand: The End of the Day",
    Year: "2000",
    Rated: "N/A",
    Released: "05 May 2000",
    Runtime: "67 min",
    Genre: "Horror",
    Director: "Daisuke Yamanouchi",
    Writer: "Daisuke Yamanouchi (screenplay)",
    Actors:
      "Kahori Asakura, Tadashi Matsuzawa, Toshimaru Murai, Salmon Sakeyama",
    Plot: "Four horny lunatics have a van and the will to rape, assault and humiliate women. They drive around and pick women to satisfy their wanton lust. Two women are captured and the sex begins, ...",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjJjNTEwNzEtNTk2NS00NTVlLWE0ZjUtZjczMjZiMmU0MTAyXkEyXkFqcGdeQXVyMTIxMDUyOTI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "3.9",
    imdbVotes: "109",
    imdbID: "tt0371941",
    Type: "movie",
    DVD: "05 May 2000",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Nobody Does It Better: The Music of James Bond",
    Year: "1997",
    Rated: "N/A",
    Released: "28 Dec 1997",
    Runtime: "50 min",
    Genre: "Documentary, Music",
    Director: "Philip Shotton",
    Writer: "N/A",
    Actors: "Don Black, John Barry, George Martin",
    Plot: "N/A",
    Language: "English",
    Country: "United Kingdom",
    Awards: "1 win",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjI3NWRlZDktZDc3Ny00MTAxLTg3N2YtNmE3ZDVlYWQ2NThhXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.5",
    imdbVotes: "103",
    imdbID: "tt0206978",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond: A BAFTA Tribute",
    Year: "2002",
    Rated: "N/A",
    Released: "28 Dec 2002",
    Runtime: "85 min",
    Genre: "Documentary",
    Director: "Stuart McDonald",
    Writer: "Steve Punt",
    Actors: "Michael Parkinson, Shirley Bassey, Ken Adam",
    Plot: "Michael Parkinson hosts a celebration of forty years of the most successful movie series ever. Tribute is paid to the talent behind the stunts, gadgets, music and design, while Pierce Brosnan, Roger Moore, Timothy Dalton, George L...",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYWY2ZGVhYjctMjNiYS00MWFiLWJmY2QtZjNiMTk3YzM2ODgwXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.8",
    imdbVotes: "100",
    imdbID: "tt0347268",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Ken Adam: Designing Bond",
    Year: "2000",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "22 min",
    Genre: "Documentary, Short",
    Director: "John Cork",
    Writer: "Bruce Scivally",
    Actors: "Charles Juroe, Roger Moore, David V. Picker, Robin Browne",
    Plot: "A look at the Oscar-winning production designer.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYThjNWE0YTUtMGEwMi00ZGIyLWIxMTgtYjFkOWU1ZWExNDY0XkEyXkFqcGdeQXVyMTQxMjk0Mg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "98",
    imdbID: "tt0321986",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond: For Real",
    Year: "2006",
    Rated: "N/A",
    Released: "10 Nov 2006",
    Runtime: "24 min",
    Genre: "Documentary",
    Director: "Rob Done",
    Writer: "N/A",
    Actors: "Daniel Craig, Martin Campbell, Chris Corbould",
    Plot: "This documentary highlights the stunts in Casino Royale (2006).",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmNiNzQxYTgtM2ZlOC00ZDAxLTg1ZDQtOGQwNDUyMTM4NzZhXkEyXkFqcGdeQXVyMjA5NjIxNDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.8",
    imdbVotes: "98",
    imdbID: "tt0929766",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Silhouettes: The James Bond Titles",
    Year: "2000",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "23 min",
    Genre: "Documentary, Short, Music",
    Director: "John Cork",
    Writer: "Bruce Scivally",
    Actors: "Patrick Macnee, Roger Moore, Ken Adam, Daniel Kleinman",
    Plot: "The making of the iconic James Bond film series title sequences, most notably a look at Maurice Binder and how his work continues to inspire the franchise and its future.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BN2NlNzFmMWEtZGJkOC00NWM3LWJkMGItMWQ4NDlkZTA4Y2I0XkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "96",
    imdbID: "tt0323978",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Ultraman R/B: Select! The Crystal of Bond",
    Year: "2019",
    Rated: "N/A",
    Released: "08 Mar 2019",
    Runtime: "72 min",
    Genre: "Action, Sci-Fi",
    Director: "Masayoshi Takesue",
    Writer: "Takao Nakano",
    Actors: "Yuya Hirata, Ryosuke Koike, Arisa Sonohara",
    Plot: "A year after the appearance of monsters, it seems the siblings are moving their separate ways, older brother Katsumi must fight again as Ultraman to save his friend from a force of evil.",
    Language: "Japanese",
    Country: "Japan",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGViYTgzNzYtZTQwYS00ZmQzLWE2MDktOTY1ZTJjNDM5NzBlXkEyXkFqcGdeQXVyNzkyMDA5MTc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "91",
    imdbID: "tt9890758",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Premiere Bond: Die Another Day",
    Year: "2002",
    Rated: "N/A",
    Released: "19 Nov 2002",
    Runtime: "48 min",
    Genre: "Documentary",
    Director: "Emma Reynolds",
    Writer: "N/A",
    Actors: "Julia Bradbury, Pierce Brosnan, Roger Moore",
    Plot: "This TV special covers the London premiere of the 20th James Bond movie, Die Another Day, and the 40th anniversary Bond celebration that coincided with it.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTcwYjg3ZjUtMzNmZC00NjQxLTg1NWEtZTgwNGU0N2VlYzE5XkEyXkFqcGdeQXVyMjA1Njg4Nw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.5",
    imdbVotes: "87",
    imdbID: "tt0385960",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Incredible World of James Bond",
    Year: "1965",
    Rated: "N/A",
    Released: "26 Nov 1965",
    Runtime: "51 min",
    Genre: "Documentary",
    Director: "Jack Haley Jr.",
    Writer: "Ian Fleming, Jack Haley Jr., Al Ramrus",
    Actors: "Alexander Scourby, Sean Connery, Ursula Andress",
    Plot: "This promotional film was aired on American television on 26 November 1965, one month before the release of Thunderball (1965). Narrated by Alexander Scourby, the 48 minute documentary aired as a one hour special. It included foot...",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTA5Y2Y5ZTItY2RlOC00NDNhLWIyNDYtYzc5OTBhNDY0OGVmXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "84",
    imdbID: "tt0438106",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Welcome to Japan, Mr. Bond",
    Year: "1967",
    Rated: "N/A",
    Released: "02 Jun 1967",
    Runtime: "50 min",
    Genre: "Action, Adventure, Drama",
    Director: "Daniel Davis",
    Writer: "Edwin Apfel",
    Actors: "Patrick Allen, Desmond Llewelyn, Lois Maxwell",
    Plot: "A made-for-television promotional documentary for the release of the James Bond movie You Only Live Twice (1967) featuring clips from the earlier 007 movies.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTgyNmMzYjQtYTJkMC00MjU4LWEzMmEtZmMxMjViMTZmYTc3XkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.6",
    imdbVotes: "82",
    imdbID: "tt0867211",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Guns of James Bond",
    Year: "1964",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "5 min",
    Genre: "Documentary, Short",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Geoffrey Boothroyd, Sean Connery",
    Plot: "Short 1964 black-and-white documentary featurette hosted by Sean Connery and featuring the real-life inspiration for the character of Q, Major Geoffrey Boothroyd with a discussion of the gun weaponry used by James Bond.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2MzMjY4ZTQtMjBhYS00OGRjLTkzZmEtZWU2ZjE0NDVhYTMxXkEyXkFqcGdeQXVyODUyMTkwOTg@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.4",
    imdbVotes: "79",
    imdbID: "tt0934852",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Terence Young: Bond Vivant",
    Year: "2000",
    Rated: "N/A",
    Released: "16 May 2000",
    Runtime: "16 min",
    Genre: "Documentary, Short",
    Director: "John Cork",
    Writer: "Bruce Scivally",
    Actors: "Richard Graydon, Michael G. Wilson, Ursula Andress, Peter R. Hunt",
    Plot: "Documentary on the career of director Terence Young.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZmI3M2ZkOGMtZjFhNy00NTI4LTk3MWEtYThhZDRjMmZjNjc2XkEyXkFqcGdeQXVyMjA5NjIxNDU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.6",
    imdbVotes: "76",
    imdbID: "tt0324209",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "True Bond",
    Year: "2007",
    Rated: "N/A",
    Released: "22 Jun 2007",
    Runtime: "52 min",
    Genre: "Documentary",
    Director: "Jane Armstrong",
    Writer: "Michael LaVoie, Gary Lang",
    Actors: "Graeme Cornies, Nick Abraham, Michael Lomenda",
    Plot: "James Bond is a worldwide icon, but is Ian Fleming's creation based on a real character? This documentary profiles the wartime exploits of Dusko Popov, a double-agent who worked for Britain and the U.S. against Germany, and reveal...",
    Language: "English",
    Country: "Canada",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYzM5NWI3M2MtMzBhMC00N2Q0LWI2ZTAtOWYzNzY2ZjQyZDE2XkEyXkFqcGdeQXVyNTA4Mzg3Nw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.6",
    imdbVotes: "71",
    imdbID: "tt1193533",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Live in Concert: Bond",
    Year: "2003",
    Rated: "N/A",
    Released: "01 Jan 2003",
    Runtime: "61 min",
    Genre: "Music",
    Director: "Mike Mansfield",
    Writer: "N/A",
    Actors: "Eos Chater, Tania Davis, Haylie Ecker",
    Plot: "N/A",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNjU2ZDNlZDAtNjRjMi00MTA2LTlhMDMtYTA2YzZhZTg4YTEwXkEyXkFqcGdeQXVyNzQwNjg4Njk@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "8.5",
    imdbVotes: "70",
    imdbID: "tt0361403",
    Type: "movie",
    DVD: "02 May 2005",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond: The First 21 Years",
    Year: "1983",
    Rated: "N/A",
    Released: "27 May 1983",
    Runtime: "60 min",
    Genre: "Documentary",
    Director: "John Longley",
    Writer: "Colin Bostock-Smith",
    Actors: "Roger Moore, Muhammad Ali, Ursula Andress",
    Plot: "Documentary which takes a light-hearted look at the screen history of agent 007, James Bond.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2QwOTFmZTQtM2JkZC00MjM4LWI5MTgtZTU3Mjc5NDBkOTVjXkEyXkFqcGdeQXVyMjM0MzAyNTU@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.0",
    imdbVotes: "68",
    imdbID: "tt0401537",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond on Location",
    Year: "2008",
    Rated: "Not Rated",
    Released: "01 Sep 2012",
    Runtime: "25 min",
    Genre: "Documentary",
    Director: "Rob Done",
    Writer: "N/A",
    Actors: "Daniel Craig, Olga Kurylenko, Mathieu Amalric",
    Plot: "Behind the scenes of shooting in various notoriously difficult locations, including interviews with producers and lead actors.",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjEzMDYwODgxNV5BMl5BanBnXkFtZTgwOTI4ODYyNjE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.7",
    imdbVotes: "66",
    imdbID: "tt1320393",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "30 Years of James Bond",
    Year: "1992",
    Rated: "N/A",
    Released: "03 Oct 1992",
    Runtime: "60 min",
    Genre: "Documentary",
    Director: "Lorna Dickinson, Alasdair Macmillan",
    Writer: "N/A",
    Actors: "Ken Adam, Albert R. Broccoli, Sean Connery",
    Plot: "N/A",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNTkxY2Y3OTMtNzM5My00ZTMyLTk4N2MtMTVlNjNjNGQ5YjIwXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.5",
    imdbVotes: "65",
    imdbID: "tt0380158",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The All-Star Bond Rally",
    Year: "1945",
    Rated: "N/A",
    Released: "10 May 1945",
    Runtime: "18 min",
    Genre: "Short, Comedy, Music",
    Director: "Michael Audley",
    Writer: "Don Quinn",
    Actors: "Bob Hope, Vivian Blaine, Jeanne Crain",
    Plot: "Inspirational documentary short film featuring Hollywood stars promoting the sales of War Bonds through songs and skits.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDExN2NjMjMtZWE2OS00MWJhLTgwNzItOWVkNWZlNTEyY2UwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMDI3OTIzOA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.2/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.2",
    imdbVotes: "63",
    imdbID: "tt0037503",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond 007",
    Year: "1983",
    Rated: "Not Rated",
    Released: "N/A",
    Runtime: "N/A",
    Genre: "Action, Adventure",
    Director: "N/A",
    Writer: "Ian Fleming (characters)",
    Actors: "N/A",
    Plot: "James Bond 007 is a 1983 side-scrolling video game developed and published by Parker Brothers for the Atari 2600, Atari 5200, ColecoVision, and Commodore 64. It is based on the James Bond film series.",
    Language: "None",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZWQyMWY1OTgtNDI5Mi00NzdlLTk5ZmYtMTM0N2MyMjQzNzgxXkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.6",
    imdbVotes: "62",
    imdbID: "tt0297197",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The World Is Not Enough: James Bond Down River",
    Year: "2000",
    Rated: "N/A",
    Released: "26 Feb 2000",
    Runtime: "25 min",
    Genre: "Documentary",
    Director: "Rob Done",
    Writer: "N/A",
    Actors: "John Gordon Sinclair, Michael G. Wilson, Michael Apted",
    Plot: "Promotional documentary filmed at the London East End Docklands area and River Thames for the filming of the opening boat chase for The World Is Not Enough (1999).",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjUyYzAzNzUtNDhjYy00ODBiLWI2NGMtNTQ0NmMzZTNiMTg1XkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.8",
    imdbVotes: "61",
    imdbID: "tt0918534",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Men Behind the Mayhem: The Special Effects of James Bond",
    Year: "2000",
    Rated: "N/A",
    Released: "16 May 2000",
    Runtime: "18 min",
    Genre: "Documentary, Short",
    Director: "John Cork",
    Writer: "Bruce Scivally",
    Actors: "Marie Clairu, Maud Adams, Tanya Roberts, Jill St. John",
    Plot: "From Dr. No (1962) to The World is Not Enough (1999), a look at the special effects in the James Bond films, and the wizardry that made them possible and some of the best in the business.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTI5ZWE1NTktMzM2Ny00YmUxLWI2ZGEtMWI1OWQ0MDUxNGRjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxMjk0Mg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.8",
    imdbVotes: "57",
    imdbID: "tt0323227",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Bond Cocktail",
    Year: "1999",
    Rated: "N/A",
    Released: "20 Nov 1999",
    Runtime: "25 min",
    Genre: "Documentary",
    Director: "Rob Done",
    Writer: "N/A",
    Actors: "Pierce Brosnan, Michael Apted, Desmond Llewelyn",
    Plot: "Promotional documentary television special filmed on the set of the James Bond movie 'The World Is Not Enough' (1999).",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjAxY2MwZTEtMzhlZC00Y2UxLWFhOGUtNTgwMGNkMTFmNzMwXkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.1",
    imdbVotes: "55",
    imdbID: "tt0918495",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Stalin's James Bond",
    Year: "2017",
    Rated: "N/A",
    Released: "11 Feb 2019",
    Runtime: "53 min",
    Genre: "Documentary, Biography, History",
    Director: "Danielle Proskar, Michael Trabitzsch",
    Writer: "N/A",
    Actors: "Alexander Absenger, Dieter Bacher, Peter Faerber",
    Plot: "An account of the troubled life of Richard Sorge (1895-1944), a Soviet spy of German origin who played a decisive role in the outcome of World War II .",
    Language: "German",
    Country: "Germany, Austria",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2E4MDRiNWMtZDA2NS00ZDBhLWJhNWMtNWUwZjVhODUyMDgzXkEyXkFqcGdeQXVyMjkyMDI4NTQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.6",
    imdbVotes: "49",
    imdbID: "tt10360916",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Designing Bond: Peter Lamont",
    Year: "2000",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "21 min",
    Genre: "Documentary, Short",
    Director: "John Cork",
    Writer: "Bruce Scivally",
    Actors: "Roger Moore, Barbara Broccoli, Vijay Amritraj, Alec Mills",
    Plot: "N/A",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGNkOTBiNmEtOTMzNi00NjkxLTg5ZTctZmY4YTI0YjYxZTU0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxMjk0Mg@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.9",
    imdbVotes: "47",
    imdbID: "tt0321987",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "A Fragile Bond",
    Year: "2019",
    Rated: "N/A",
    Released: "14 Apr 2020",
    Runtime: "95 min",
    Genre: "Drama",
    Director: "Adeline Darraux",
    Writer: "Judith Norman, Isabel Sebastian",
    Actors: "Barbara Schulz, Thierry Godard, Jessyrielle Massengo",
    Plot: "Mina was adopted from Ethiopia by Judith and Lionel, a married couple who already were the parents of a biological daughter. Though she was abandoned by her mother as a baby, it didn't really seem to have much of an impact on her....",
    Language: "French",
    Country: "France",
    Awards: "1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BODUwYjU3NWQtZGJiYS00ZDQzLTk5MTAtNWZiMTgzOTVkMWNlXkEyXkFqcGdeQXVyOTEwNTkyNjE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.4",
    imdbVotes: "40",
    imdbID: "tt10081112",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Noi non siamo come James Bond",
    Year: "2012",
    Rated: "N/A",
    Released: "12 Apr 2013",
    Runtime: "73 min",
    Genre: "Documentary",
    Director: "Mario Balsamo",
    Writer: "Mario Balsamo, Guido Gabrielli",
    Actors: "Daniela Bianchi",
    Plot: "It was back in 1985 when Guido and Mario, good buddies, decided to take their first trip together. Thirty years later, the memories of that period overlap with their present life, for both marked by a long struggle against cancer....",
    Language: "Italian",
    Country: "Italy",
    Awards: "1 win & 1 nomination",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BY2EyNmU5NmMtYWE5Ny00MmZmLWI2NjAtYjk5MDNjY2VmNGM4XkEyXkFqcGdeQXVyMDk2Mzc2MA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.4/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.4",
    imdbVotes: "39",
    imdbID: "tt2421314",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Premium Bond with Mark Gatiss and Matthew Sweet",
    Year: "2015",
    Rated: "N/A",
    Released: "28 Oct 2015",
    Runtime: "55 min",
    Genre: "Documentary",
    Director: "Tim Niel",
    Writer: "N/A",
    Actors: "Mark Gatiss, Matthew Sweet, Irvin Allen",
    Plot: "N/A",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTA3ZTlhYjYtZjc4MC00ZjIzLWFjZTgtYjAyYTZmZjYzMWMyXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.3",
    imdbVotes: "39",
    imdbID: "tt5156674",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Skyfall: Modern Day Bond",
    Year: "2013",
    Rated: "N/A",
    Released: "01 Jul 2013",
    Runtime: "N/A",
    Genre: "Documentary",
    Director: "N/A",
    Writer: "Ben Patterson",
    Actors: "Colin Salmon, Javier Bardem, Daniela Bianchi",
    Plot: "N/A",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjViZWZlOGEtMDNhMS00MDJiLTg1OTUtYmY0ZjMxZWNjZDY1XkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.7",
    imdbVotes: "37",
    imdbID: "tt3136962",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Mat Bond Malaya",
    Year: "2021",
    Rated: "N/A",
    Released: "20 Jul 2021",
    Runtime: "88 min",
    Genre: "Action, Comedy",
    Director: "Nabil Ahmad",
    Writer: "Nabil Ahmad",
    Actors: "Naqiu, Elizabeth Tan, Farid Azmeir",
    Plot: "Mat dreams of becoming a secret agent at the M6 Building where he works. A zombie outbreak occurs, and Mat has to save the world including his crush Bondi.",
    Language: "Malay",
    Country: "Malaysia",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZGY0ZDI1YzQtZDNmYS00OTBlLWFmNTAtZjRkNzI4ZDAzMGIyXkEyXkFqcGdeQXVyODc1ODUxNjE@._V1_SX300.jpg",
    Ratings: [],
    Metascore: "N/A",
    imdbRating: "N/A",
    imdbVotes: "37",
    imdbID: "tt15067882",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond Omega Seamaster Diver 300M Television Commercial",
    Year: "2018",
    Rated: "N/A",
    Released: "22 Sep 2018",
    Runtime: "1 min",
    Genre: "Short, Adventure",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Daniel Craig",
    Plot: "Looking every inch the gentleman as Bond surfaces for air in OMEGA's new campaign. Who else could make a wet-suit look this stylish?",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTU4OTA2M2QtMTkxNC00ZTA5LWFhY2QtYzIzOWIwZGFlZTAwXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.0",
    imdbVotes: "36",
    imdbID: "tt11974562",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond 303",
    Year: "1985",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "N/A",
    Genre: "Action, Adventure, Crime",
    Director: "Ravi Tandon",
    Writer: "N/A",
    Actors: "Jeetendra, Parveen Babi, Tom Alter",
    Plot: "Terrorist attacks take place all over the world by unknown rockets so an Indian agent, Bond 303, is called to solve the mystery behind it.",
    Language: "Hindi",
    Country: "India",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYmYwZTQ2NmEtMDE4OS00YzdkLWI0MmEtN2NjN2Y2NTM2NjUxXkEyXkFqcGdeQXVyNDQwOTAzNw@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.1",
    imdbVotes: "35",
    imdbID: "tt0448392",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond: Licence to Thrill",
    Year: "1987",
    Rated: "N/A",
    Released: "29 Jun 1987",
    Runtime: "51 min",
    Genre: "Documentary",
    Director: "Mike Ward",
    Writer: "George Perry",
    Actors: "Nick Owen, Lois Maxwell, Ursula Andress",
    Plot: "Promotional documentary television special celebrating the 25th Anniversary of James Bond and release of the then new James Bond film 'The Living Daylights' (1987).",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTJhOWI2MjgtOTdiZi00MWUyLWE5Y2UtZDM4NTQ0OTg5OGZhXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "35",
    imdbID: "tt0918535",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Ian Fleming: Where Bond Began",
    Year: "2008",
    Rated: "N/A",
    Released: "19 Oct 2008",
    Runtime: "59 min",
    Genre: "Documentary",
    Director: "Louise Hooper",
    Writer: "N/A",
    Actors: "Joanna Lumley, Jonathan Pryce, Geoffrey Boothroyd",
    Plot: "N/A",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYjk4NDZiMGUtZTQzMS00OWMzLThmNDQtN2NmOWJkZTRmMTBlXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "34",
    imdbID: "tt1311040",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond on Location",
    Year: "2008",
    Rated: "N/A",
    Released: "01 Sep 2012",
    Runtime: "25 min",
    Genre: "Documentary, Short",
    Director: "Rob Done",
    Writer: "N/A",
    Actors: "Daniel Craig, Olga Kurylenko, Mathieu Amalric, Gemma Arterton",
    Plot: "Behind the scenes of shooting in various notoriously difficult locations, including interviews with producers and lead actors.",
    Language: "English",
    Country: "UK",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjEzMDYwODgxNV5BMl5BanBnXkFtZTgwOTI4ODYyNjE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.7",
    imdbVotes: "34",
    imdbID: "tt2647730",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond 1973: The Lost Documentary",
    Year: "1973",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "21 min",
    Genre: "Documentary, Short",
    Director: "Christopher Doll",
    Writer: "N/A",
    Actors: "Albert R. Broccoli, Harry Saltzman, Guy Hamilton",
    Plot: "Original 1973 short promotional documentary on the making of the 8th James Bond movie Live and Let Die (1973).",
    Language: "English",
    Country: "United Kingdom",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMDMwM2ExOTMtNmY4MS00ZWFmLTg2ZmUtMjllZTRmMWFkYjI0XkEyXkFqcGdeQXVyMjQzODk5MDI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.0/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.0",
    imdbVotes: "28",
    imdbID: "tt0924421",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Tough Bond",
    Year: "2013",
    Rated: "Not Rated",
    Released: "09 May 2014",
    Runtime: "85 min",
    Genre: "Documentary, Drama",
    Director: "Austin Peck, Anneliese Vandenberg",
    Writer: "N/A",
    Actors: "N/A",
    Plot: "As traditional Kenyan villages give way to exploding city slums, community bonds dissolve and youth turn to the street. Followed over three years, four kids addicted to huffing glue create their own fierce family in this unflinchi...",
    Language: "Swahili, English",
    Country: "United States",
    Awards: "2 nominations",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTU1NjgyMjQ4MF5BMl5BanBnXkFtZTgwMjA0MzU4MTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.9/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.9",
    imdbVotes: "28",
    imdbID: "tt2555386",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Naruto: The Broken Bond",
    Year: "2008",
    Rated: "T",
    Released: "18 Nov 2008",
    Runtime: "N/A",
    Genre: "Adventure",
    Director: "N/A",
    Writer: "Masashi Kishimoto (manga), Masashi Kishimoto (story)",
    Actors: "Maile Flanagan, Yuri Lowenthal, Kate Higgins, Steve Blum",
    Plot: "N/A",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjQ3ZWRjNmEtYWEyMi00ZmZiLThhNDUtYTNjZjQ3ZDBiMzY4XkEyXkFqcGdeQXVyNTk5Nzg0MDE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.7",
    imdbVotes: "28",
    imdbID: "tt5252222",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "7up Commercial James Bond Theme",
    Year: "2001",
    Rated: "N/A",
    Released: "09 Jul 2001",
    Runtime: "1 min",
    Genre: "Short, Action",
    Director: "John Frankenheimer",
    Writer: "N/A",
    Actors: "Eric Pilch",
    Plot: "Biker Thief steals a bottle of 7UP from a youth then he chases the thief down in a tank.",
    Language: "None",
    Country: "Canada",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWUxZjFhODctYjVkNi00YTZlLTk3MzgtMTY3Njc4MzY2NjA4XkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.3/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.3",
    imdbVotes: "27",
    imdbID: "tt2634508",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond 007",
    Year: "1997",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "N/A",
    Genre: "Action",
    Director: "N/A",
    Writer: "Ian Fleming (characters and universe)",
    Actors: "N/A",
    Plot: "N/A",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOTM3NjI4ZjktYWQyMC00Yjc0LTg5MmEtYTQ0NThjOTczMTYwXkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.7/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.7",
    imdbVotes: "27",
    imdbID: "tt0924448",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond 007: The Stealth Affair",
    Year: "1990",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "N/A",
    Genre: "Action, Adventure, Crime",
    Director: "Paul Cuisset",
    Writer: "Ian Fleming (characters and universe)",
    Actors: "N/A",
    Plot: "N/A",
    Language: "English",
    Country: "France",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BM2RmY2RhYzItMWVjMi00MmJiLTlkMDItOWE5NmRkN2IwN2VjXkEyXkFqcGdeQXVyNzg5OTk2OA@@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "7.1",
    imdbVotes: "27",
    imdbID: "tt0924450",
    Type: "game",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "James Bond 007 Vs. The Joker",
    Year: "2013",
    Rated: "Not Rated",
    Released: "12 Apr 2013",
    Runtime: "5 min",
    Genre: "Animation, Short, Action",
    Director: "Michael Horvath",
    Writer: "Michael Horvath",
    Actors: "Michael Horvath",
    Plot: "The Joker causes a massive power outage at the Superdome during Super Bowl XLVII in an attempt to take control of the event and unleash unthinkable chaos. Now, Agent 007, James Bond, is the only man who can stop him.",
    Language: "English",
    Country: "United States",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTE1ZWI2NTctZTcwMi00ZTU4LWI1ZTctN2U2MjQ2MWFjOGQxXkEyXkFqcGdeQXVyMTg5NzA2NjI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "4.1/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "4.1",
    imdbVotes: "26",
    imdbID: "tt2949144",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Skyfall: Shooting Bond",
    Year: "2013",
    Rated: "N/A",
    Released: "12 Feb 2013",
    Runtime: "60 min",
    Genre: "Documentary",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Charlie Adcock, Javier Bardem, Nikki Berwick, Barbara Broccoli",
    Plot: "N/A",
    Language: "English",
    Country: "UK",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTE1ZWI2NTctZTcwMi00ZTU4LWI1ZTctN2U2MjQ2MWFjOGQxXkEyXkFqcGdeQXVyMTg5NzA2NjI@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "6.8",
    imdbVotes: "26",
    imdbID: "tt2705708",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Bond V Batman: Age of Vengeance",
    Year: "2015",
    Rated: "N/A",
    Released: "21 May 2015",
    Runtime: "21 min",
    Genre: "Short, Action, Adventure, Comedy, Fantasy",
    Director: "Mike Barkhoff",
    Writer:
      "Mike Barkhoff, Braydon James, Adam Kaufman, Grant R. Weldon, Austin Schafer",
    Actors: "Mike Barkhoff, Braydon James, Adam Kaufman, Josh Kuiper",
    Plot: "In the biggest fight of modern day history, James Bond and Batman face off against one another.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMmM3YjY2OGUtYTAwMS00YWFiLTk4ZjUtZDEyMDc5MmRjYWYwXkEyXkFqcGdeQXVyNTg4OTQ0NzQ@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "9.5/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "9.5",
    imdbVotes: "26",
    imdbID: "tt12622400",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "The Magic Bond",
    Year: "1956",
    Rated: "N/A",
    Released: "22 Jan 1956",
    Runtime: "26 min",
    Genre: "Short",
    Director: "Robert Altman",
    Writer: "Robert Altman",
    Actors: "Joe Adelman, Owen Bush, Kermit Echols",
    Plot: "The Veterans of Foreign Wars as a fraternal and social organization, with emphasis on their projects that benefit community life and cohesion.",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYzFmZWI2NjUtYzA1Zi00Y2M2LWI3YzQtNjAxZmM4NzJhMDQ2XkEyXkFqcGdeQXVyMjYzNTk1NTE@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "3.8/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "3.8",
    imdbVotes: "25",
    imdbID: "tt0416947",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Er Conde Bond 007 y Pico",
    Year: "2012",
    Rated: "N/A",
    Released: "17 Aug 2012",
    Runtime: "N/A",
    Genre: "Comedy",
    Director: "Benjamin Rausseo",
    Writer: "Benjamin Rausseo",
    Actors: "Andreina Castro, Laura Chimaras, David Hey",
    Plot: "N/A",
    Language: "Spanish",
    Country: "Venezuela",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNGE1MGMzYmUtMDAzYS00ZTZiLWFlZjAtMjQxYWJmMTcyYjFiXkEyXkFqcGdeQXVyNjg3MDM4Mzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.6/10",
      },
    ],
    Metascore: "N/A",
    imdbRating: "5.6",
    imdbVotes: "24",
    imdbID: "tt2604350",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "N/A",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "GoldenEye: Building a Better Bond",
    Year: "2006",
    Rated: "N/A",
    Released: "N/A",
    Runtime: "9 min",
    Genre: "Documentary, Short",
    Director: "N/A",
    Writer: "N/A",
    Actors: "Barbara Broccoli, Pierce Brosnan, Martin Campbell, Chris Corbould",
    Plot: "Teaser promotional documentary made for theaters and exhibitors, shot in 1994 during pre-production to promote the then upcoming James Bond movie GoldenEye (1995).",
    Language: "English",
    Country: "USA",
    Awards: "N/A",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BYTUwODUwZjItYzNiYS00ZTUxLThlOGUtZTg1YjA5OTBkNmNiXkEyXkFqcGdeQXVyMTY1MTcxMzc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.2/10",
      },
    ],
  },
];
